'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cheque
    Public Property Id As Integer
    Public Property ChequeNo As Nullable(Of Integer)
    Public Property PartyName As String
    Public Property AMOUNT As Nullable(Of Decimal)
    Public Property ChequeBookNo As String

End Class
